#!/usr/bin/env ruby
require 'coderay'

def fetch_options
  Dir["#{__dir__}/txt/*.txt"].map do |str|
    File.basename(str, File.extname(str))
  end
end

def color(string)
  CodeRay.scan(string, :ruby).terminal
end

def print_ref(name)
  file = "#{__dir__}/txt/#{name}.txt"
  ref_data = open file
  ref_data.each { |line| print color(line) }
  ref_data.close
end

def system_out(passed_arg)
  options = fetch_options
  if options.include?(passed_arg)
    print_ref(passed_arg)
  else
    puts color("Usage: refy [shortcut list]\nPossible shortcut lists:")
    options.each { |option| puts ' ' * 4 + color(option) }
  end
end

system_out(ARGV[0])
