#!/usr/bin/env ruby
require 'yaml'
require 'coderay'

def print_ref (name)
  file = "#{__dir__}/txt/#{name}.txt"
  ref_data = open file

  ref_data.each do |line|
    print CodeRay.scan(line, :ruby).terminal
  end

  ref_data.close
end

print_ref(ARGV[0])
